/* Vues sans mutation : les valeurs utilisateur sont échappées systématiquement. */
(function (root) {
  'use strict';
  const M = root.CarnetModel;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]));
  const fmt = value => Number(value).toLocaleString('fr-FR', { maximumFractionDigits: 2 });
  // Ne jamais afficher un seuil atteint alors que la valeur réelle lui est inférieure.
  const percent = value => {
    if (value == null) return '—';
    const rounded = Math.round(value * 10) / 10;
    const boundary = [25, 50, 75, 100].find(t => value < t && rounded >= t);
    return boundary ? 'Moins de ' + boundary + ' %' : Number(rounded).toLocaleString('fr-FR', { maximumFractionDigits: 1 }) + ' %';
  };
  const scoreClass = value => value == null ? 'empty-score' : value < 25 ? 'na' : value < 50 ? 'eca' : value < 75 ? 'pa' : 'ta';
  const sortedStudents = cls => [...cls.students].sort((a, b) => a.name.localeCompare(b.name, 'fr', { sensitivity: 'base' }));
  const path = (cls, tab = 'entry', control = '', student = '') => '#class/' + cls.id + '/' + tab + (control ? '/' + control : '') + (student ? '/' + student : '');
  const button = (text, action, cls = 'button', attrs = '') => `<button type="button" class="${cls}" data-action="${action}" ${attrs}>${text}</button>`;
  const empty = (title, text, action = '') => `<div class="empty-state"><span class="empty-symbol" aria-hidden="true">▤</span><h2>${title}</h2><p>${text}</p>${action}</div>`;
  function home(data) {
    return `<div class="page-heading"><div><p class="eyebrow">UN PEU MOINS DE PAPIER, UN PEU PLUS DE CLARTÉ</p><h1>Mes classes<span class="heading-dot">.</span></h1><p>Vos élèves, leurs progrès. Tout simplement.</p></div>${button('+ Ajouter une classe', 'new-class', 'button primary')}</div>
      ${data.classes.length ? `<div class="class-grid">${data.classes.map((cls, i) => `<article class="class-card"><div class="class-card-top"><span class="class-icon tone-${i % 3}" aria-hidden="true">${esc(cls.name.slice(0, 2))}</span><span class="subtle">${cls.controls.length} contrôle${cls.controls.length > 1 ? 's' : ''}</span></div><h2>${esc(cls.name)}</h2><p>${cls.students.length} élève${cls.students.length > 1 ? 's' : ''}</p><a class="button primary full" href="${path(cls)}">Saisir des résultats <span aria-hidden="true">→</span></a><div class="class-links"><a href="${path(cls, 'summary')}">Synthèse</a><a href="${path(cls, 'manage')}">Gérer la classe</a></div></article>`).join('')}</div>` : `<div class="welcome"><div class="welcome-art" aria-hidden="true"><div class="paper"><span></span><b>Les progrès<br>prennent forme.</b><i></i><i></i><i></i><div>✓</div></div></div><div><p class="eyebrow">BIENVENUE DANS VOTRE CARNET</p><h2>Votre première classe,<br>et c’est parti.</h2><p>Ajoutez une classe, collez la liste de vos élèves, puis créez votre premier contrôle.</p>${button('Créer ma première classe →', 'new-class', 'button primary')}</div></div>`}
      <aside class="backup-reminder"><span aria-hidden="true">↥</span><div><strong>Votre carnet reste sur cet appareil.</strong><p>Pensez à télécharger une sauvegarde après une séance de saisie.</p></div><a href="#backup">Sauvegarder</a></aside>`;
  }
  function shell(cls, tab, content) {
    return `<a class="back-link" href="#">← Mes classes</a><div class="class-heading"><div><p class="eyebrow">MON CARNET DE COMPÉTENCES</p><h1>${esc(cls.name)}</h1></div><span class="count-chip">${cls.students.length} élèves</span></div><nav class="class-tabs" aria-label="Dans cette classe">${[['entry', 'Saisir'], ['summary', 'Synthèse'], ['manage', 'Gérer']].map(([key, label]) => `<a href="${path(cls, key)}" ${key === tab ? 'aria-current="page"' : ''}>${label}</a>`).join('')}</nav>${content}`;
  }
  function chooseControl(cls) {
    if (!cls.students.length) return empty('Commençons par les élèves', 'Collez votre liste de classe, un nom par ligne.', `<a class="button primary" href="${path(cls, 'manage')}">Ajouter mes élèves →</a>`);
    return `<div class="section-heading"><div><h2>Quel contrôle souhaitez-vous saisir ?</h2><p>Choisissez un contrôle, puis prenez votre première copie.</p></div>${button('+ Nouveau contrôle', 'new-control', 'button primary')}</div>${cls.controls.length ? `<div class="control-grid">${[...cls.controls].reverse().map(c => {
      const complete = cls.students.filter(s => M.studentProgress(c, s.id).complete === c.skills.length).length;
      return `<a class="control-card" href="${path(cls, 'entry', c.id)}"><div><span class="eyebrow">${c.date ? esc(new Date(c.date + 'T12:00:00').toLocaleDateString('fr-FR')) : 'CONTRÔLE'}</span><h3>${esc(c.name)}</h3><p>${c.skills.length} compétence${c.skills.length > 1 ? 's' : ''} · ${complete} / ${cls.students.length} copies complètes</p><progress value="${complete}" max="${cls.students.length}" aria-label="${complete} copies complètes sur ${cls.students.length}"></progress></div><span aria-hidden="true">→</span></a>`;
    }).join('')}</div>` : empty('Votre premier contrôle', 'Choisissez les compétences et indiquez les points possibles.', button('Créer un contrôle', 'new-control', 'button primary'))}`;
  }
  function statusText(status, max) {
    if (status.state === 'empty') return 'Pas encore saisi · hors synthèse';
    if (status.state === 'invalid') return 'Vérifiez les valeurs : nombres positifs ou zéro, 2 décimales maximum.';
    if (status.state === 'excess') return `${fmt(status.sum)} / ${fmt(max)} points · ${fmt(status.sum - max)} point(s) en trop. Hors synthèse.`;
    if (status.state === 'partial') return `${fmt(status.sum)} / ${fmt(max)} points · encore ${fmt(max - status.sum)} à répartir. Hors synthèse.`;
    return `${fmt(status.sum)} / ${fmt(max)} points · Réussite : ${percent(status.score)}`;
  }
  function skillInput(cls, control, student, spec) {
    const skill = cls.skills.find(s => s.id === spec.skillId), result = control.results[student.id]?.[skill.id] || M.blank();
    const status = M.resultStatus(result, spec.max);
    return `<section class="skill-entry" aria-labelledby="title-${skill.id}"><div class="skill-entry-heading skill-${skill.color}"><h3 id="title-${skill.id}">${esc(skill.name)}</h3><span>${fmt(spec.max)} pts</span></div><div class="level-grid">${M.LEVELS.map(level => {
      const invalid = M.parsePoints(result[level]).kind === 'invalid';
      return `<div class="level-field ${level.toLowerCase()}"><label for="point-${skill.id}-${level}">${level}<small>× ${fmt(M.WEIGHTS[level])}</small></label><input id="point-${skill.id}-${level}" type="text" inputmode="decimal" autocomplete="off" maxlength="32" placeholder="—" value="${esc(result[level])}" data-point data-skill="${skill.id}" data-level="${level}" aria-label="${esc(student.name)}, ${esc(skill.name)}, ${level}" aria-describedby="status-${skill.id}" ${invalid ? 'aria-invalid="true"' : ''}></div>`;
    }).join('')}</div><p id="status-${skill.id}" class="entry-status ${status.state}" aria-live="polite" aria-atomic="true">${statusText(status, spec.max)}</p></section>`;
  }
  function entry(cls, control, student) {
    const students = sortedStudents(cls), index = students.findIndex(s => s.id === student.id), progress = M.studentProgress(control, student.id);
    return `<div class="entry-top"><div><label for="control-select">Contrôle</label><select id="control-select">${cls.controls.map(c => `<option value="${c.id}" ${c.id === control.id ? 'selected' : ''}>${esc(c.name)}</option>`).join('')}</select></div><a class="text-link" href="${path(cls)}">Tous les contrôles</a></div>
      <div class="entry-layout"><aside class="student-panel"><p class="eyebrow">UNE COPIE À LA FOIS</p><label for="student-select">Élève <span class="subtle">${index + 1} sur ${students.length}</span></label><select id="student-select">${students.map(s => `<option value="${s.id}" ${s.id === student.id ? 'selected' : ''}>${esc(s.name)}</option>`).join('')}</select><div class="student-name"><span aria-hidden="true">✎</span><h2>${esc(student.name)}</h2></div><p id="student-progress">${progress.complete} / ${progress.total} compétences complètes</p><p class="helper">Reportez les points de la copie. Les cases vides valent zéro dès que tous les points sont répartis.</p><details class="level-help"><summary>Que signifient les niveaux ?</summary><p>NA : non acquis<br>ECA : en cours d’acquisition<br>PA : partiellement acquis<br>TA : totalement acquis</p></details></aside><div class="skills-stack">${control.skills.map(s => skillInput(cls, control, student, s)).join('')}<p class="helper">Les saisies incomplètes ou à corriger restent enregistrées, mais ne comptent pas dans la synthèse.</p></div></div>
      <nav class="student-pager" aria-label="Passer à une autre copie">${index > 0 ? `<a class="button secondary" href="${path(cls, 'entry', control.id, students[index - 1].id)}">← Précédent</a>` : '<button class="button secondary" disabled>← Précédent</button>'}<span>${index + 1} / ${students.length}</span>${index < students.length - 1 ? `<a class="button primary" href="${path(cls, 'entry', control.id, students[index + 1].id)}">Élève suivant →</a>` : `<a class="button primary" href="${path(cls, 'summary')}">Voir la synthèse →</a>`}</nav>`;
  }
  function summaryCards(cls, query = '', sort = 'az') {
    const normalize = s => s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase('fr');
    const students = sortedStudents(cls).filter(s => normalize(s.name).includes(normalize(query.trim())));
    if (sort === 'za') students.reverse();
    return `<p class="result-count">${students.length} fiche${students.length > 1 ? 's' : ''} · seules les compétences entièrement saisies sont comptées.</p>${students.length ? `<div class="summary-grid">${students.map(student => {
      const totals = M.aggregate(cls, student.id);
      return `<article class="summary-card"><h3>${esc(student.name)}</h3><dl>${cls.skills.map(skill => {
        const t = totals.skills[skill.id];
        return `<div><dt><span class="skill-dot skill-${skill.color}" aria-hidden="true"></span>${esc(skill.name)}<small>${t.count ? `${t.count} évaluation${t.count > 1 ? 's' : ''} · ${fmt(t.max)} pts` : 'Pas encore évaluée'}${t.excluded ? ` · ${t.excluded} saisie(s) à terminer` : ''}</small></dt><dd class="score ${scoreClass(t.score)}">${percent(t.score)}</dd></div>`;
      }).join('')}</dl></article>`;
    }).join('')}</div>` : empty('Aucun élève trouvé', query ? 'Essayez un autre nom.' : 'Ajoutez les élèves dans « Gérer ».')}`;
  }
  function summary(cls, query, sort) {
    return `<div class="section-heading"><div><h2>Les progrès de chaque élève</h2><p>Une moyenne pondérée par les points possibles.</p></div>${button('Imprimer', 'print', 'button secondary no-print')}</div><div class="summary-tools no-print"><div><label for="summary-search">Rechercher un élève</label><input type="search" id="summary-search" placeholder="Un nom, un prénom…" value="${esc(query)}"></div><div><label for="summary-sort">Ordre des fiches</label><select id="summary-sort"><option value="az" ${sort === 'az' ? 'selected' : ''}>Nom A → Z</option><option value="za" ${sort === 'za' ? 'selected' : ''}>Nom Z → A</option></select></div></div><p class="legend"><span class="na">0 à &lt;25 %</span><span class="eca">25 à &lt;50 %</span><span class="pa">50 à &lt;75 %</span><span class="ta">75 à 100 %</span></p><div id="summary-results">${summaryCards(cls, query, sort)}</div>`;
  }
  function manage(cls) {
    return `<div class="section-heading"><div><h2>Ma classe, en ordre</h2><p>Préparez vos élèves et vos prochains contrôles.</p></div>${button('Renommer la classe', 'rename-class', 'button secondary')}</div><div class="manage-grid"><section class="panel"><div class="section-heading"><h2>Mes élèves <span class="subtle">${cls.students.length}</span></h2>${button('+ Ajouter', 'new-students', 'button primary')}</div>${cls.students.length ? `<ul class="item-list">${sortedStudents(cls).map(s => `<li><strong>${esc(s.name)}</strong><div class="item-actions">${button('Modifier', 'rename-student', 'small-button', `data-id="${s.id}" aria-label="Modifier le nom de ${esc(s.name)}"`)}${button('×', 'delete-student', 'small-button danger', `data-id="${s.id}" aria-label="Supprimer ${esc(s.name)}"`)}</div></li>`).join('')}</ul>` : `<p>Collez toute votre liste en une fois : un élève par ligne.</p>${button('Ajouter mes élèves', 'new-students', 'button secondary')}`}</section><section class="panel"><div class="section-heading"><h2>Mes contrôles <span class="subtle">${cls.controls.length}</span></h2>${button('+ Créer', 'new-control', 'button primary')}</div>${cls.controls.length ? `<ul class="item-list controls-list">${[...cls.controls].reverse().map(c => `<li><div><strong>${esc(c.name)}</strong><p>${c.skills.length} compétence(s)${c.date ? ' · ' + esc(new Date(c.date + 'T12:00:00').toLocaleDateString('fr-FR')) : ''}</p><a href="${path(cls, 'entry', c.id)}">Saisir les résultats →</a></div><div class="item-actions">${button('Modifier', 'edit-control', 'small-button', `data-id="${c.id}" aria-label="Modifier ${esc(c.name)}"`)}${button('×', 'delete-control', 'small-button danger', `data-id="${c.id}" aria-label="Supprimer ${esc(c.name)}"`)}</div></li>`).join('')}</ul>` : '<p>Créez un contrôle, choisissez ses compétences et leurs points possibles.</p>'}</section></div><div class="danger-zone"><p>Supprimer la classe retire également ses élèves, ses contrôles et leurs résultats.</p>${button('Supprimer cette classe', 'delete-class', 'button danger')}</div>`;
  }
  function backup(data, recovery = false) {
    const counts = data ? `${data.classes.length} classe(s) · ${data.classes.reduce((n, c) => n + c.students.length, 0)} élève(s) · ${data.classes.reduce((n, c) => n + c.controls.length, 0)} contrôle(s)` : '';
    return `${recovery ? '' : '<a class="back-link" href="#">← Mes classes</a>'}<div class="page-heading"><div><p class="eyebrow">PRENDRE SOIN DE VOTRE CARNET</p><h1>${recovery ? 'Retrouvons votre carnet' : 'Mes sauvegardes'}</h1><p>${recovery ? 'Les données existantes ont été conservées. Rien n’a été effacé.' : 'Une petite habitude, pour garder l’esprit tranquille.'}</p></div></div><div class="backup-grid">${data ? `<section class="panel backup-panel"><span class="large-icon" aria-hidden="true">↥</span><h2>Garder une copie</h2><p>Téléchargez tout votre carnet : classes, élèves, contrôles et résultats.</p><p class="helper">${counts}</p>${button('Sauvegarder mes données', 'export', 'button primary full')}<p class="helper">Gardez ce fichier dans un endroit sûr, idéalement aussi sur un autre appareil. Il contient les noms et résultats de vos élèves.</p></section>` : ''}<section class="panel backup-panel"><span class="large-icon" aria-hidden="true">↧</span><h2>Retrouver une sauvegarde</h2><p>Choisissez un fichier de sauvegarde. Son contenu sera vérifié avant de vous proposer de remplacer le carnet.</p><label class="button secondary file-button" for="restore-file">Choisir ma sauvegarde<input id="restore-file" type="file" accept=".json,application/json"></label><p id="restore-feedback" role="status"></p></section><section class="panel backup-panel"><h2>Revenir à la copie précédente</h2><p>L’appareil garde une copie avant la dernière modification enregistrée. Vous pourrez la vérifier avant de la rétablir.</p>${button('Examiner la copie précédente', 'previous', 'button secondary')}${recovery ? button('Conserver les données pour obtenir de l’aide', 'raw-export', 'button secondary full') : ''}</section></div><p class="helper">Sur un autre appareil ou dans un autre navigateur, ouvrez le carnet puis restaurez votre sauvegarde. Ouvrez toujours l’application au même emplacement.</p>`;
  }
  function dialogForm(title, fields, submit, extra = '') {
    return `<form id="edit-form"><div class="dialog-heading"><h2 id="dialog-title">${title}</h2>${button('×', 'close-dialog', 'icon-button', 'aria-label="Fermer"')}</div>${fields}<p id="form-error" class="form-error" role="alert"></p>${extra}<div class="dialog-actions">${button('Annuler', 'close-dialog', 'button secondary')}<button class="button primary" type="submit">${submit}</button></div></form>`;
  }
  function controlFields(cls, control) {
    return `<label for="control-name">Nom du contrôle</label><input id="control-name" name="name" maxlength="120" required value="${esc(control?.name || '')}" placeholder="Ex. Pythagore"><label for="control-date">Date <span class="subtle">facultative</span></label><input id="control-date" name="date" type="date" value="${esc(control?.date || '')}"><fieldset class="skill-config"><legend>Compétences évaluées</legend>${cls.skills.map(s => {
      const spec = control?.skills.find(x => x.skillId === s.id);
      return `<div class="skill-config-row skill-${s.color}"><label class="check-label"><input type="checkbox" name="skill" value="${s.id}" ${spec ? 'checked' : ''}>${esc(s.name)}</label><div ${spec ? '' : 'hidden'}><label for="max-${s.id}">Points possibles</label><input id="max-${s.id}" name="max-${s.id}" type="text" inputmode="decimal" maxlength="12" placeholder="Ex. 5" value="${spec ? fmt(spec.max).replace(/\s/g, '') : ''}" ${spec ? '' : 'disabled'}></div></div>`;
    }).join('')}</fieldset>${control ? '<p class="helper">Modifier un barème peut rendre des saisies incomplètes. Retirer une compétence supprime ses saisies pour ce contrôle ; une confirmation vous sera demandée.</p>' : ''}`;
  }
  root.CarnetViews = { esc, fmt, percent, scoreClass, sortedStudents, path, button, empty, home, shell, chooseControl, entry, statusText, summary, summaryCards, manage, backup, dialogForm, controlFields };
})(globalThis);
